name: Backend CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      # Node setup
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Install dependencies
      - run: npm install

      # Lint
      - run: npm run lint

      # Unit tests
      - run: npm test

      # Package Lambda functions
      - run: zip -r function.zip ./src

      # Deploy Lambda
      - name: Deploy Lambda
        run: |
          aws lambda update-function-code \
            --function-name MyLambdaFunction \
            --zip-file fileb://function.zip \
            --region us-east-1
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
