name: Backend CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-deploy-backend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Deploy each service
      - name: Deploy backend services
        run: |
          for service in user-srv media-srv recommendation-srv; do
            echo "Deploying $service..."
            cd services/$service

            # Install dependencies
            npm install

            # Lint
            npm run lint || echo "Lint failed in $service"

            # Unit tests
            npm test || echo "Tests failed in $service"

            # Package Lambda
            zip -r function.zip ./src

            # Deploy Lambda
            aws lambda update-function-code \
              --function-name $service \
              --zip-file fileb://function.zip \
              --region us-east-1

            # Go back to repo root
            cd ../../
          done
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
