name: Frontend CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies
      - run: npm install
        working-directory: apps/mobile-app

      # Step 4: Lint
      - run: npm run lint
        working-directory: apps/mobile-app

      # Step 5: Unit tests
      - run: npm test
        working-directory: apps/mobile-app

      # Step 6: Build project
      - run: npm run build
        working-directory: apps/mobile-app

      # Step 7: Deploy to Netlify
      - name: Deploy to Netlify
        uses: nwtgck/actions-netlify@v1.2
        with:
          publish-dir: apps/mobile-app/build
          production-deploy: true
        env:
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
