name: Frontend CI/CD

on:
  push:
    branches: [dev, main]
  pull_request:
    branches: [dev, main]

jobs:
  build-and-test-frontend:
    runs-on: ubuntu-latest
    steps:
      # Step 1: Checkout code
      - uses: actions/checkout@v3

      # Step 2: Setup Node
      - uses: actions/setup-node@v3
        with:
          node-version: 18

      # Step 3: Install dependencies (including devDependencies like eslint)
      - name: Install dependencies
        run: npm ci
        working-directory: apps/mobile-app

      # Step 4: Lint
      - name: Lint
        run: |
          if npm run lint; then
            echo "Lint passed"
          else
            echo "Lint failed but continuing"
          fi
        working-directory: apps/mobile-app

      # Step 5: Unit tests
      - name: Run tests
        run: |
          if npm test; then
            echo "Tests passed"
          else
            echo "Tests failed but continuing"
          fi
        working-directory: apps/mobile-app

      # Step 6: Build project
      - name: Build
        run: npm run build
        working-directory: apps/mobile-app
